export const missionSectionObjOne = {
    id: 'mission',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine2: "Our Mission, Vision, & Values",
    headline2: "Mission",
    description2: "Empower individuals who prioritize their health to become competent in self-management of their symptoms.",
    headline3: "Vision",
    description3: "Enhance movement through skilled interventions that will successfully target your impairments.",
    headline4: "Values",
    description4: "Courage — In spite of fear, movement is and will always be the best medicine. Even though you may have recently gone through a traumatic experience, our experts will ensure to get you moving well. ",
    description5: "Integrity — Doing what is right, all the time. When Dr. Rick prescribes exercises and/or mobility treatments, he is doing it with your goals in mind. Dr. Rick will explain every step of the way what you’re performing, how to perform it and why you’re performing it.",
    description6: "Transparency — Effective communication is the key to success. Dr. Rick will have honest and upfront conversations about your plan of care, how to attain your goals and the smoothest path to take. No fluff involved here.",
    description7: "Patience — This is a virtue we can all work on. There is no one-size fits all approach when it comes to Physical Therapy. Dr. Rick ensures that every exercise and mobility treatment prescribed to you is EXACTLY what you need. As long as you perform them as outlined in your regimen, your goals will surely be met.",
    imgStart: false,
    img: require('../../images/herologo.jpg').default,
    img2: require('../../images/8.jpg').default,
    alt: 'mission',
    primary: true,
    darkText: false
}
