export const homeObjOne = {
    id: 'about',
    lightBg: true,
    lightText: false,
    lightTextDesc: true,
    topLine: "Who Are We?",
    headline: "2nd To None PT",
    description: "Dr. Rick Chavez is a SoCal native and a U.S. Army Veteran. He has played all different types of sports throughout his life and has been performing strength and conditioning for the last 10 years of his life. As a Physical Therapist, Dr. Rick understands how to manage symptoms and prescribe therapeutic exercises to alleviate pain. As a Certified Strength and Conditioning Specialist (CSCS), Dr. Rick can help propel your physical and mental toughness to the next level!",
    buttonLabel: 'Continue',
    imgStart: false,
    img: require('../../images/1.jpg').default,
    alt: 'about',
    dark: true,
    primary: true,
    darkText: false,
};

export const homeObjTwo = {
    id: 'about',
    lightBg: true,
    lightText: false,
    lightTextDesc: true,
    topLine: "2nd to None PT | San Marcos, CA",
    headline: "Why Us?",
    description: "As an avid thrill-seeker, Dr. Rick knows what it takes to perform at a high-level when playing a multitude of sports such as: soccer, mountain biking, Olympic weightlifting, snowboarding, CrossFit, skateboarding, sprinting, football, etc. Plus, Dr. Rick will be the only healthcare professional managing your plan of care and he will be with you throughout every minute of your treatment",
    imgStart: false,
    img: require('../../images/6.jpg').default,
    alt: 'testimonials',
    dark: false,
    buttonLabel: 'Read More',
    primary: false,
    darkText: false,
};
export const homeObjTestimonial1 = {
    id: 'testimonials',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: "Testimonials",
    headline: "Brenda S. of Los Angeles, CA | Yelp Review",
    description: "Dr. Rick Chavez is AMAZING! Had major back pain with having a baby last year and after just one visit felt a whole lot better! Will definitely be visiting more often. He's very knowledgeable and made everything super comfortable! Thanks again!",
    imgStart: false,
    img: require('../../images/whitelogo.jpg').default,
    alt: 'testimonials',
    dark: false,
    buttonLabel: 'Read More',
    primary: false,
    darkText: false,
};
export const homeObjTestimonial2 = {
    id: 'testimonials',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: "Yelp Review",
    headline: "Cade L. of San Diego, CA | Yelp Review",
    description: "Excellent PT with a focus on results, and patient safety.  If I could give more than 5-stars, I absolutely would!  Anyone dealing with chronic pain, or lingering injuries, would be well off to give Dr Rick a call!",
    imgStart: false,
    img: require('../../images/7.jpg').default,
    alt: '',
    dark: false,
    buttonLabel: 'Read More',
    primary: false,
    darkText: false,
};

export const homeObjThree = {
    id: 'social-media',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: "Connect With Us on Social Media",
    headline: "Dr. Rick & Rebeca | 2nd To None PT",
    description: "Rick and his wife live in Escondido, CA with their son and two crazy dogs. They live in a great neighborhood and cherish their time with their little family. Their business, 2nd to None PT, generates 100’s of pain-free patients each year. They provide a quality of service that is second to none and allows their patients to return to doing the things they love to do. Rick lives a life that is both humble and fulfilling. He worships God daily, enjoys working with his wife and awesome patients and has the time freedom to enjoy those great relationships in the great outdoors of southern California. Click below to follow along the journey!",
    buttonLabel: 'Our Links',
    imgStart: false,
    img: require('../../images/rick.jpg').default,
    alt: 'herologo',
    dark: true,
    primary: true,
    darkText: false,
    path: 'social-media'
};

export const homeObjFour = {
    id: 'pt-everywhere',
    lightBg: true,
    lightText: false,
    lightTextDesc: true,
    topLine: "Self Scheduling",
    headline: "Online Booking has never been so Quick & Easy",
    description: "Are you ready to begin your pain free, active lifestyle? With self-scheduling, book an appointment anytime, anywhere. With 2nd To None Physical Therapy, know care fits around your schedule.",
    buttonLabel: 'Get Started',
    imgStart: false,
    img: require('../../images/12.jpg').default,
    alt: 'herologo',
    dark: true,
    primary: true,
    darkText: false,
};

export const homeObjFive = {
    id: 'resources',
    lightBg: true,
    lightText: false,
    lightTextDesc: true,
    topLine: "Resources",
    headline: "2nd To None offers free resources for everyone",
    description: "2nd to None PT supports numerous non-profit organizations both financially and through their time and effort. 2nd to None PT enjoys focusing their efforts on giving back to the less fortunate and Veterans with mentorship and guidance so that they may pursue post-professional training and higher positions of power in their communities.",
    buttonLabel: 'Browse Resources',
    imgStart: false,
    img: require('../../images/resources.jpg').default,
    alt: 'resources',
    dark: true,
    primary: true,
    darkText: false,
};

export const homeObjSix = {
    id: 'social-media',
    lightBg: true,
    lightText: false,
    lightTextDesc: true,
    topLine: "More About Dr. Rick",
    headline: "2nd To None Physical Therapy | San Diego, CA",
    description: "Rick Chavez is a successful and highly regarded clinician, U.S. Army Veteran and a southern California native. He and his wife, Rebeca, work together to help people get out of pain, find out why they are in pain and to educate them on how to keep the pain away for good! Dr. Rick lives a life that is both humble and fulfilling. He worships God daily, enjoys working with his wife and awesome patients and has the time freedom to enjoy those great relationships in the great outdoors of southern California. Rick learned a lot about selfless service during his time in the U.S. Army. Rick recently attained his Certified Strength and Conditioning Specialist (CSCS) so that he may provide more in-depth knowledge during his treatments. He continues to give back his knowledge, time and skills so that others may have greater opportunities and live a more fulfilling life. ",
    buttonLabel: 'Follow Rick on IG',
    imgStart: false,
    img: require('../../images/10.jpg').default,
    alt: 'herologo',
    dark: true,
    primary: true,
    darkText: false,
};
export const homeObjSeven = {
    id: 'pt-everywhere',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: "PT Everywhere",
    headline: "Create an Account or Login",
    description: "Schdeduling has never been easier, begin by logging in or creating your free account. ",
    buttonLabel: "Let's Go",
    imgStart: false,
    img: require('../../images/herologo.jpg').default,
    alt: 'herologo',
    dark: true,
    primary: true,
    darkText: false,
};